export { default as Input } from "./Input.vue";
export { default as InputPhone } from "./InputPhone.vue";
export { default as InputCountry } from "./InputCountry.vue";
export { default as InputBeneficiaryCountry } from "./InputBeneficiaryCountry.vue";
export { default as InputFile } from "./InputFile.vue";
export { default as InputAmount } from "./InputAmount.vue";
export { default as InputReceivingCurrency } from "./InputReceivingCurrency.vue";
export { default as InputBusinessCategory } from "./InputBusinessCategory.vue";
// export { default as InputFileExpress } from "./InputFileExpress.vue";
export { default as Select } from "./Select.vue";
export { default as RadioGroup } from "./RadioGroup.vue";
export { default as Switch } from "./Switch.vue";
export { default as TextArea } from "./TextArea.vue";
export { default as StepBullets } from "./StepBullets.vue";
export { default as ButtonAPI } from "./ButtonAPI.vue";
